Create part1_exam
AT-PHPIntership/toeic-test pull request #121
Opened 2017-04-28 06:50 UTC by at-tinhdang

Create questions in Part 1

2017-04-28 07:34 UTC, ghost requested changes
pls check my cmt

2017-04-28 07:34 UTC, at-vienle commented on app/Http/Controllers/Backend/ExamController.php
> +    public function storePart1(PostPart1Request $request, $id)
I think you should move this function to QuestionController

2017-04-28 07:34 UTC, at-vienle commented on app/Http/Controllers/Backend/ExamController.php
> +        $questions = collect([]);
this variables is not used

2017-04-28 07:34 UTC, at-vienle commented on resources/views/backend/questions/create/part1.blade.php
> +                      <option value="0">{{trans('questions.keyA')}}</option>
pls define a const `NUMBER_OF_ANSWER`   =  4 in Question model, then in the view loop and render follow by that const

2017-04-28 07:34 UTC, at-vienle commented on resources/views/backend/questions/create/part1.blade.php
> +                    <input type="text" name="question[{{$i}}][content][]" value="{{trans('questions.keyA')}}" readonly="">
Define the const number of answer and don't need these input

2017-04-28 07:34 UTC, at-vienle commented on app/Http/Controllers/Backend/ExamController.php
> +                $requestQuestionsI = $requestQuestions['question'][$i];
why you name it `$requestQuestionsI`, this name is not good

2017-04-28 07:34 UTC, at-vienle commented on app/Models/Exam.php
> +    const FINISH_ING = 2;
What does it mean?

2017-04-28 08:33 UTC, at-tinhdang commented on app/Models/Exam.php
> +    const FINISH_ING = 2;
It mean when exam don't finished , can continue  edit & add this exam

2017-05-08 02:17 UTC, ghost approved these changes
LGTM

2017-05-08 02:17 UTC, merged